.TH "src Directory Reference" 3 "Mon Feb 2 2015" "Version 0.1" "Multimedia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgraphique\fP"
.br
.ti -1c
.RI "directory \fBheaders\fP"
.br
.ti -1c
.RI "directory \fBServer\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfilm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmultimedia\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmultimedia_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBphoto\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvideo\&.cpp\fP"
.br
.in -1c
