.TH "MainWindow" 3 "Mon Feb 2 2015" "Version 0.1" "Multimedia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.PP
This is the main window of the program\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String argv[])"
.br
.RI "\fIMain function of the program\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the main window of the program\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow\&.MainWindow ()\fC [inline]\fP"

.PP
Constructor\&. Creates the main window\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void MainWindow\&.main (Stringargv[])\fC [inline]\fP, \fC [static]\fP"

.PP
Main function of the program\&. Just creates the window\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Multimedia from the source code\&.
