.TH "Photo::DeleterPhoto" 3 "Mon Feb 2 2015" "Version 0.1" "Multimedia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photo::DeleterPhoto \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBPhoto\fP *photo)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Multimedia from the source code\&.
