.TH "Video::DeleterVideo" 3 "Tue Feb 3 2015" "Version 0.1" "Multimedia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Video::DeleterVideo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBVideo\fP *video)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Multimedia from the source code\&.
