.TH "Video" 3 "Tue Feb 3 2015" "Version 0.1" "Multimedia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Video \- 
.PP
This class represents a video file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <video\&.h>\fP
.PP
Inherits \fBMultimedia\fP\&.
.PP
Inherited by \fBFilm\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeleterVideo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual unsigned int \fBgetLength\fP (void) const "
.br
.RI "\fILength getter\&. \fP"
.ti -1c
.RI "virtual void \fBsetLength\fP (unsigned int newLength)"
.br
.ti -1c
.RI "virtual string \fBprint\fP (void) const "
.br
.RI "\fIPrint description\&. \fP"
.ti -1c
.RI "virtual void \fBplay\fP (void) const "
.br
.RI "\fIDisplay the multimedia file on screen\&. \fP"
.ti -1c
.RI "virtual void \fBwrite\fP (ostream &stream) const "
.br
.RI "\fISerialize the multimedia object\&. \fP"
.ti -1c
.RI "virtual void \fBread\fP (istream &stream)"
.br
.RI "\fIRead from a serialized object\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVideo\fP (const \fBVideo\fP &)"
.br
.ti -1c
.RI "\fBVideo\fP (void)"
.br
.RI "\fIDefault Constructor\&. \fP"
.ti -1c
.RI "\fBVideo\fP (string name, unsigned long date, string pathname, unsigned int length)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "virtual \fB~Video\fP (void)"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "virtual \fBVideo\fP * \fBclone\fP (void) const "
.br
.RI "\fIClone the video\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMultimediaManager\fP"
.br
.ti -1c
.RI "class \fBDeleterVideo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents a video file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Video::Video (void)\fC [protected]\fP"

.PP
Default Constructor\&. Defaut constructor of a video\&. 
.SS "Video::Video (stringname, unsigned longdate, stringpathname, unsigned intlength)\fC [protected]\fP"

.PP
Constructor\&. Constructor of a video\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP : Name of the video\&. 
.br
\fIdate\fP : Date when the file is added\&. 
.br
\fIpathname\fP : Path to the video\&. 
.br
\fIlength\fP : Length of the video in seconds\&. 
.RE
.PP

.SS "Video::~Video (void)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Destructor\&. Default destructor of this class\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBVideo\fP * Video::clone (void) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Clone the video\&. 
.PP
\fBReturns:\fP
.RS 4
Return a copy of the given video\&. 
.RE
.PP

.PP
Implements \fBMultimedia\fP\&.
.PP
Reimplemented in \fBFilm\fP\&.
.SS "unsigned int Video::getLength (void) const\fC [virtual]\fP"

.PP
Length getter\&. Get the length of the video\&.
.PP
\fBReturns:\fP
.RS 4
The length of the video\&. 
.RE
.PP

.SS "string Video::print (void) const\fC [virtual]\fP"

.PP
Print description\&. Print the description of the file to the standard output 
.PP
\fBReturns:\fP
.RS 4
Return a string which contains the file description\&. 
.RE
.PP

.PP
Reimplemented from \fBMultimedia\fP\&.
.SS "void Video::read (istream &stream)\fC [virtual]\fP"

.PP
Read from a serialized object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP : the input stream where the object will be read\&. 
.RE
.PP

.PP
Implements \fBMultimedia\fP\&.
.PP
Reimplemented in \fBFilm\fP\&.
.SS "void Video::write (ostream &stream) const\fC [virtual]\fP"

.PP
Serialize the multimedia object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP : the output stream where the object will be written\&. 
.RE
.PP

.PP
Implements \fBMultimedia\fP\&.
.PP
Reimplemented in \fBFilm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multimedia from the source code\&.
